#!/bin/bash

sp=()
extra=()

while read -r line; do
    sp+=("$line")
done < "text.txt"

n=${sp[0]}

unset sp[0]

for ((i=0; i < $n; i++)) do
    extra+=(0)
done

k=1
answer=1

for item in "${sp[@]}"; do
    read -ra buf <<< "$item"
    num1=${buf[0]}
    num1=${num1-1}
    num2=${buf[1]}
    num2=${num2-1}
    if [ ${extra[$num1]} -eq 0 ] && [${extra[$num2]} -eq 0]; then
        extra[$num1]=k
        extra[$num2]=k
        k=${k+1}
        answer=${answer+1}
    elif [${extra[$num1]} != 0 ] && [${extra[$num2]} -eq 0]; then
         extra[$num2]=${extra[$num1]}
    elif [${extra[$num1]} -eq 0 ] && [${extra[$num2]} != 0]; then
         extra[$num1]=${extra[$num2]}
    elif [${extra[$num1]} != 0 ] && [${extra[$num2]} != 0]; then
         for ((i=0; i < ${#extra[@]}; i++); do
             if [${extra[i]} -eq ${extra[num2]}]; then
                 extra[i]=${extra[num1]}
             fi
         done
         answer=${answer-1}
    fi
done

